### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by huang-x-h** [expo/babel-preset-expo#3]
Hi

I am using `babel-preset-expo` and when import `@expo/vector-icons`, run jest test error

`.babelrc`

```
{
  "presets": ["babel-preset-expo"],
  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source"]
    }
  }
}
```

Detail error message

```
 PASS  src/switch/__tests__/Switch.js
 FAIL  src/toast/__tests__/Toast.js
  ● Test suite failed to run

    /Users/project_path/node_modules/@expo/vector-icons/Ionicons.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import glyphMap from './vendor/react-native-vector-icons/glyphmaps/Ionicons.json';
                                                                                             ^^^^^^
    
    SyntaxError: Unexpected token import
      
      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:321:12)
      at Object.<anonymous> (src/icon/Icon.js:6:15)
      at Object.<anonymous> (src/toast/Toast.js:7:11)

```

Thanks for any help

**Comment by dikaiosune** [comment]
Can you provide your jest configuration please?

**Comment by huang-x-h** [comment]
Thank you for your reply. 

Yestoday i change this and do not throw the SyntaxError again.

```diff
"jest": {
    "preset": "react-native",
    "coverageDirectory": "./coverage/",
    "collectCoverageFrom": [
      "src/**/*.js",
      "!src/index.js",
      "!src/helpers/*.js"
    ],
    "collectCoverage": true,
+   "transformIgnorePatterns": [
+      "node_modules/(?!react|@expo|expo)"
+   ],
    "globals": {
      "__DEV__": true
    }
  },
```

**Comment by dikaiosune** [comment]
@ide is this something we should include in jest-expo?

**Comment by ide** [comment]
jest-expo's config should (as in both "it would be desirable" and "I think it already does") specify what to transform but maybe we're excluding `@expo/vector-icons` and other Expo modules.

**Comment by asciifaceman** [comment]
`"node_modules/(?!react|@expo|expo|mobx-react)"`

This is actually not working for me, it did up until vector-icons
